# NumPy

1. Given a list[1,2,3,4,5] create a numpy array from it ?

In [3]:
import numpy as np
l=[1,2,3,4,5]
arr=np.array(l)
print(arr)

[1 2 3 4 5]


2. Create an array of 10 zeros

In [5]:
a= np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3.Generate an array with values from 10 to 50?

In [7]:
a=np.arange(50,101)
print(a)

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


4. Givn an array arr= np.array[10,20,30,40,50]Extract the first and last element?

In [9]:
ar= np.array([10,20,30,40,50])
print(ar[0])
print(ar[-1])

10
50


5. Given two arrays, a= np.array ([1,2,3]) and b=np.array([4,5,6]),perform element wise addition?

In [11]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


6. Given  a= np.array([1,2]) and b=np.array([3,4]) calculte dot product of these two vector 

In [13]:
a= np.array([1,2])
b=np.array([3,4])
print(np.dot(a,b))

11


7. Given  a= np.array([10,20,30,40,50]) Extract element from index 1 to 3 (Inclusive of start, exculsive of end)?

In [15]:
a= np.array([10,20,30,40,50]) 
print(a[0:3])

[10 20 30]


8. Given a= np.array([10,20,30,40,50]) Reverse the element in the array using slicing ?

In [17]:
a= np.array([10,20,30,40,50])
print(a[::-1])

[50 40 30 20 10]


9. Replace all element in a= np.array([10,20,30,40,50]) Greater than 25 with 0?

In [19]:
a= np.array([10,20,30,40,50])
a[a>25]=0
print(a)

[10 20  0  0  0]


10.Replace all odd numbers in the array with -1

In [21]:
a=np.array([2,3,4,5,6,7,8,9])
a[a % 2 != 0]=-1
print(a)

[ 2 -1  4 -1  6 -1  8 -1]


11. Calculating the square root of each element in an array?

In [23]:
a=np.array([2,3,4,5,6,7,8,9])
print(a**2)

[ 4  9 16 25 36 49 64 81]


12. Given a= np.array([3,5,1,2,4]), find the min and max value and their respective indices?

In [25]:
a= np.array([3,5,1,2,4])
print(a.min())
print(a.max())

1
5


13. Given a= np.array([10,15,20,25,30,]), filter out element that are greater than 20?

In [27]:
a= np.array([10,15,20,25,30,])
b=a[a>20]
print(b)

[25 30]


14. Given a= np.array([10,20,30,40,50]) select only values that are greater than 10 and less than 25?

In [29]:
a= np.array([10,20,30,40,50])
b=a[(a>10) & (a<25)]
print(b)


[20]


15. Given a= np.array([4,6,8,10,12]) Find indices of all element greater than 8?

In [31]:
a= np.array([4,6,8,10,12])
ind=np.where(a>8)
print("Indices",ind)

Indices (array([3, 4]),)


16. How can you set a random seed in NumPy to ensure reproducibility?

In [51]:
np.random.seed(42)
print(np.random.randint(1, 100, 100))


[52 93 15 72 61 21 83 87 75 75 88 24  3 22 53  2 88 30 38  2 64 60 21 33
 76 58 22 89 49 91 59 42 92 60 80 15 62 62 47 62 51 55 64  3 51  7 21 73
 39 18  4 89 60 14  9 90 53  2 84 92 60 71 44  8 47 35 78 81 36 50  4  2
  6 54  4 54 93 63 18 90 44 34 74 62 14 95 48 15 72 78 87 62 40 85 80 82
 53 24 26 89]


17. Given two array  a= np.array ([1,2,3]) and b=np.array([4,5,6]) calculate the mean and standard deviation of the element in an array ?

In [55]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Mean and Standard Deviation of a
mean_a = np.mean(a)
std_a = np.std(a)

# Mean and Standard Deviation of b
mean_b = np.mean(b)
std_b = np.std(b)

print("Mean of a:", mean_a)
print("Standard Deviation of a:", std_a)

print("Mean of b:", mean_b)
print("Standard Deviation of b:", std_b)


Mean of a: 2.0
Standard Deviation of a: 0.816496580927726
Mean of b: 5.0
Standard Deviation of b: 0.816496580927726


18. Given two array a= np.array ([1,2,3,4,5]) and b=np.array([4,5,6,7,8]) Find the:
    - Intersection of a and b
    - Union of  and b

In [69]:
a= np.array ([1,2,3,4,5])
b=np.array([4,5,6,7,8])

# Intersection of a and b
print(np.intersect1d(a,b))

# Union of and b
print(np.union1d(a,b))

[4 5]
[1 2 3 4 5 6 7 8]


19. Given a= np.array([10,20,30,40,50])
    - Find the max, min & mean of the above given array?
      

In [85]:
a= np.array([10,20,30,40,50])
m1=np.max(a)
m2=np.min(a)
a=np.mean(a)

print("max",m1)
print("Min",m2)
print("Mean",a)

max 50
Min 10
Mean 30.0


20. Find the index of the max & min elements of the above mentioned array?

In [88]:

a = np.array([10, 20, 30, 40, 50])

# Index of max and min elements
max_index = np.argmax(a)
min_index = np.argmin(a)

print("Index of Max Element:", max_index)
print("Index of Min Element:", min_index)


Index of Max Element: 4
Index of Min Element: 0
